server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location / {
        index index.html;
        try_files $uri $uri/ =404;
    }

    location /downloads/ {
        add_header Content-Disposition "attachment";
    }
}
